[package]
name = "aminus"
version = "0.1.0"
edition = "2021"
description = "genshin calculation library"
authors = ["Lambdev"]

[lib]
name = "aminus"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.45.0", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
reqwest = { version = "0.12.15", features = ["json"] }
anyhow = "1.0" 
pyo3 = "0.25.1"
wasm-bindgen = "0.2.100"
