[package]
name = "aminus-py"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "aminus_py"

[dependencies]
aminus = { path = "../.." }

[dependencies.pyo3]
version = "0.25"
features = ["extension-module"]

[build-dependencies]
maturin = "1.5"